### ISSUE TITLE
Bug report / バグ報告: textures are not being extracted to a folder

### ISSUE THREAD

**Issue by skyace65** [saturday06/VRM-Addon-for-Blender#111]
**Describe the bug / バグについて**

When importing a VRM model textures are not being extracted to a folder when the option is checked. The folder is being created but there's nothing in it

**To Reproduce / バグの再現方法**
1. Export a character from vroid studio as a VRM
2. Open Blender with the vroid addon
3. go to import VRM
4. Check the "extract texture images into the folder" option
5. Import the model

**Expected behavior / 期待する動作**
After importing a model the textures from it should be in a folder

**Desktop (please complete the following information) / PC環境情報**
- OS: Windows 10
- Blender: 3.1.2
- Addon Version: 2.3.8

**Comment by saturday06** [comment]
Hi
Thanks for reporting! This bug has been fixed in the latest version 2.3.10 https://github.com/saturday06/VRM_Addon_for_Blender/releases/tag/2_3_10 . Please try it !

**Comment by skyace65** [comment]
It's better. Textures are being extracted to a `.vrm.textures` folder now. But they are also being saved to the same folder the .blend file is in.

**Comment by saturday06** [comment]
Thanks!
The fix has been released in 2.3.11 https://github.com/saturday06/VRM_Addon_for_Blender/releases/tag/2_3_11 . Please try it!

**Comment by skyace65** [comment]
It's working perfectly now! Thanks for the fix, and thanks for the great addon!

**Comment by valentinegb** [comment]
I am using version 2.10.2 and I'm still experiencing this issue. The folder is created in the same directory as the vrm I import, but there is nothing in the folder. I also get this error in Blender while importing:
![Screenshot 2022-11-13 at 11 48 22 AM](https://user-images.githubusercontent.com/35977727/201541230-5bcb16a4-567e-4d6c-818f-5d87bb1086a2.png)
I am using Blender 3.3.1 on macOS Ventura 13.1

**Comment by zhump** [comment]
> 我使用的是 2.10.2 版，但我仍然遇到这个问题。文件夹创建在和我导入的vrm同级目录下，但是文件夹里什么都没有。导入时我也在 Blender 中收到此错误： 我在 macOS Ventura 13.1 上使用 Blender 3.3.1 ![屏幕截图 2022-11-13 11 48 22 AM](https://user-images.githubusercontent.com/35977727/201541230-5bcb16a4-567e-4d6c-818f-5d87bb1086a2.png)

me to ，help～～

**Comment by alaborde29** [comment]
I'm still experiencing this issue today. please reopen the issue
