### ISSUE TITLE
Bug report: When exporting to VRM 0.x, T-pose transformation is not applied to shapekeys; lip sync animations could affect arms

### ISSUE THREAD

**Issue by Kakurady** [saturday06/VRM-Addon-for-Blender#335]
## Describe the bug
When exporting to VRM 0.x, T-pose transformation is not applied to shapekeys; if an avatar with A-pose resting pose is selected for export, viseme animations will affect arms.

## To Reproduce
1. Import Avatar with A-pose
1. Pose Armature as T-pose and save to pose library
https://github.com/saturday06/VRM-Addon-for-Blender/assets/138435/93c18af0-647b-478c-8ce2-661b6335b683
1. Set T-pose for VRM export
1. Add new blend shape proxy and set a shape key 
https://github.com/saturday06/VRM-Addon-for-Blender/assets/138435/21da1f25-4eb5-4108-b142-7ca7c3c70318
2. Export as VRM 0.x
3. Import VRM into new Blender file
4. Observe resting pose is T-pose
5. Adjust shape keys value and observe morph target remains in A-pose 
https://github.com/saturday06/VRM-Addon-for-Blender/assets/138435/d6e2d3b6-b8fb-4aac-9d26-4a4d9b3fa7aa
7. Import VRM into application with lip sync, such as VNyan or VirtualMotionCapture
8. Observe lip sync animations also move arms
https://github.com/saturday06/VRM-Addon-for-Blender/assets/138435/49c0f90a-1ba2-4b6b-8481-a961af972ae4

## Expected behavior
- T-pose transformation should be applied to shapekeys
- Lip sync animation should not affect arms

## Screenshots
![vlcsnap-2023-10-09-07h59m36s276](https://github.com/saturday06/VRM-Addon-for-Blender/assets/138435/832553a6-a627-4e20-a5fa-73d45ffa49d9)

## Desktop (please complete the following information)
- Blender 3.6.4
- Addon 2.20.7

## Additional context
Does not affect VRM 1 export.

Does not affect avatars already in T-pose.

**Comment by saturday06** [comment]
Thanks for reporting!

Dangerous bug. I will fix it.

**Comment by saturday06** [comment]
This bug has been fixed in the add-on version 2.20.84 that I just released. Please try it out!

**Comment by superkido511** [comment]
This bug still happens with the latest version 3.11.2 and Blender 4.5.0. Shapekeys distort the meshes when export to VRM from blender. 
Without shapekey:

<img width="220" height="149" alt="Image" src="https://github.com/user-attachments/assets/511b579e-864e-4223-87a4-179674ebe2ea" />

With shapekey:
<img width="276" height="173" alt="Image" src="https://github.com/user-attachments/assets/181fe8c5-8501-4ff3-968c-b9a6a4f34f25" />

**Comment by saturday06** [comment]
@superkido511 Thanks for the report! The bug has been resolved on my end. For investigation purposes, could you please share your blend file (deleted all meshes except the one in the screenshot section)?

**Comment by superkido511** [comment]
@saturday06 It seem that it only happen when I used old three vrm version, I tried using newer version with ExpressionManager and didn't have this issue. So it's most likely not a bug from this extension

**Comment by saturday06** [comment]
Thank you for your investigation!
